### ISSUE TITLE
Publish data in csv format

### ISSUE THREAD

**Issue by Vanuan** [kavaleriy/budget#1]
Currently you publish database dump. It would be nice if you generated csv files out of that.

**Comment by Vanuan** [comment]
Found csv files in https://github.com/kavaleriy/budget/tree/master/db directory. Not very intuitive place.

**Comment by begemotvalery** [comment]
Hi John,
that was requested by one of our clients,
still, we have plans to add api for extracting raw data in future.
thanks,
valeriy
