### ISSUE TITLE
додати в візуалізацію бюджетів і карт соцмережі

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#135]
![socmeregi](https://cloud.githubusercontent.com/assets/18190755/16518231/5c273d24-3f8a-11e6-8251-8b13d68f9eb9.png)

шарінг на фейсбук.

**Comment by andy-vin** [comment]
Візуалізація бюджетів - http://prntscr.com/c3wi1k
Карти - http://prntscr.com/c3wpuo

**Comment by andy-vin** [comment]
Зроблено
