### ISSUE TITLE
Частина файлів пропала в модулі карта

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#159]
В Дніпропетровська частина файлів пропала з бек-енду як в нас так і в них, але на фронт-енді на сайті ОДА і міста дніпра інформація є.
![bug2](https://cloud.githubusercontent.com/assets/18190755/16617130/8725cf6e-438a-11e6-85b3-7ec75908bcab.png)

**Comment by andy-vin** [comment]
Зброблено
Буде доступне після перевантаження сервера

**Comment by vtarnay** [comment]
готово
