### ISSUE TITLE
Не створюється об'єднана візуалізація на профілі міста

### ISSUE THREAD

**Issue by karelin2005** [kavaleriy/budget#18]
http://openbudget.in.ua/public/budget_files/55a818d06b617309df652500?locale=uk

**Comment by Quicks** [comment]
embeded code невірний?

2016-04-06 17:28 GMT+03:00 karelin2005 <notifications@github.com>:

**Comment by karelin2005** [comment]
Не знаю, але люди вставити не можуть на сайти.

**Comment by Quicks** [comment]
fix embeded code
