### ISSUE TITLE
Зробити у редакторі вирівнювання картинок по розміру новини чи статті

### ISSUE THREAD

**Issue by karelin2005** [kavaleriy/budget#20]
Зробити можливим вставляти картинки посередині, а не по лівому краю (щоб вони виглядали естетичніше) і щоб вони ніколи не вилазили за межі тексту (як у “бюджет на мапі”)
Також вирівняти з текстом заголовок

**Comment by Quicks** [comment]
Для того щоб виставити зображення по центру необхідно наступне:
1.Завантажити зображення 
2.Поставити курсор перед зображенням
3.Вибрати меню "Параграф"
![selection_001](https://cloud.githubusercontent.com/assets/10288310/14493387/e37a29c0-018d-11e6-8181-ae3c0a4ece8d.png)
4.Насолоджуватись

**Comment by karelin2005** [comment]
Я не хочу його ставити збоку або по центру, я хочу по ширині тексту у вікні.
