### ISSUE TITLE
Футер вилазить на середину сторінки.

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#259]
Необхідно закріпити футер, внизу. ))) 
![image](https://cloud.githubusercontent.com/assets/18250100/17292334/210468e0-57f2-11e6-9e79-cd3ec9def2ee.png)

**Comment by andy-vin** [comment]
Перевіряйте на **http://obqa.m2i.work/**
Версії різняться на http://obqa.m2i.work/ та openbudget.in.ua
http://prntscr.com/c06c0a

**Comment by karelin20005** [comment]
Це якраз з тестового сайту

**Comment by andy-vin** [comment]
готово - http://prntscr.com/c70dvx

**Comment by vtarnay** [comment]
вроді ок
