### ISSUE TITLE
Лого Eidos та лого партнерів на візуалізаціях.

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#285]
![image](https://cloud.githubusercontent.com/assets/18250100/17442311/daad8e4a-5b3d-11e6-9c1e-2e7cb20af525.png)
Робити після консультації.

**Comment by karelin20005** [comment]
![image](https://cloud.githubusercontent.com/assets/18250100/17442179/347d6f04-5b3d-11e6-85b7-771bf6754f60.png)

**Comment by vtarnay** [comment]
Логтип краще розміщувати внизу справа, для прикладу накидав варіант для розміщення логотипів наших партнерів ![kladbishche logo](https://cloud.githubusercontent.com/assets/18190755/17774309/bd7ba550-655b-11e6-89bf-8c5b13258de7.jpg)

**Comment by vtarnay** [comment]
Додати поле - останнє оновлення
![kartinka2](https://cloud.githubusercontent.com/assets/18190755/18211297/a737325a-7145-11e6-93e9-c6663a2b09a7.png)

**Comment by vtarnay** [comment]
Дублювання
