### ISSUE TITLE
Користувачі не можуть додавати документи

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#294]
![1ea5ff7567a20e4f6a84b66d1411c285b6e646a37b44dbd59a pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/18250100/17516803/3c7c18c2-5e49-11e6-959b-aa001894f0df.png)

**Comment by karelin20005** [comment]
У модулі документи, користувач не може додавати документи видає таку помилку.

**Comment by vtarnay** [comment]
Done
