### ISSUE TITLE
Випадають пікселі при масштабуванні модуля "Порівняння" 

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#299]
![default](https://cloud.githubusercontent.com/assets/18250100/17619383/c35c8656-608d-11e6-82d8-18be4c50909e.jpg)

**Comment by andy-vin** [comment]
зроблено - http://prntscr.com/c5vesy, http://prntscr.com/c5vf4e, http://prntscr.com/c5vfbg

**Comment by vtarnay** [comment]
готово
