### ISSUE TITLE
Календар - не відображуються img для не зареестрованого користувача

### ISSUE THREAD

**Issue by kavaleriy** [kavaleriy/budget#3]
http://openbudget.in.ua/widgets/calendar/pie_cycle/559546726b61730717180000
вибрати event 
правий блок показує теги замість картинки <img alt="City" src="/assets/calendar/city.png" />

**Comment by HellLena** [comment]
fixed https://github.com/kavaleriy/budget/commit/c6aca8e98d02b3dc828f79644c1059a310608213
