### ISSUE TITLE
Підкажіть як адмініструвати банери?

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#301]
![baner](https://cloud.githubusercontent.com/assets/18190755/17625261/be899268-60b0-11e6-859a-db3915fa23d0.png)

**Comment by Sorey** [comment]
Готово
вихід на список банерів - http://prntscr.com/c7847l, http://prntscr.com/c784hy
вигляд адміна - http://prntscr.com/c785sz
редагування - http://prntscr.com/c786be, http://prntscr.com/c786sg

**Comment by vtarnay** [comment]
готово
