### ISSUE TITLE
В модулі громадьский бюджет пофіксити видалення (при нажатті помилку викидає)

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#303]
![default](https://cloud.githubusercontent.com/assets/18190755/17627746/ff247392-60ba-11e6-9c67-924f4dac1e06.png)

**Comment by andy-vin** [comment]
Готово - http://prntscr.com/c6jicw, http://prntscr.com/c6jkuk

**Comment by vtarnay** [comment]
готово
