### ISSUE TITLE
Бюджетна карта. Вказівник попапу не співпадає з піном на мапі. Людині кажеться, що попап відноситься до іншого об'єкту.

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#307]
![image](https://cloud.githubusercontent.com/assets/18250100/17668373/9d0cc6ec-6311-11e6-9466-2904e573805e.png)

**Comment by Sorey** [comment]
Готово - http://prntscr.com/c8vg4o

**Comment by vtarnay** [comment]
вроді Done
