### ISSUE TITLE
Модуль Календар. Не вистачає поля автор у адмінці. І якщо місто завантажило декілька календарів, то який з них активний на профілі міста?

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#309]
![image](https://cloud.githubusercontent.com/assets/18250100/17669001/9ab1aaf4-6314-11e6-9f25-caa06d841822.png)

**Comment by Sorey** [comment]
Готово - http://prntscr.com/c7qwdn, http://prntscr.com/c7qzrb

**Comment by vtarnay** [comment]
Done
