### ISSUE TITLE
Профіль міста. Документи не підтягується іконка.

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#312]
![image](https://cloud.githubusercontent.com/assets/18250100/17698956/b268cddc-63c6-11e6-8f69-76cf749c84eb.png)

**Comment by andy-vin** [comment]
Скиньте іконки на випадки, коли немає типу документу та на архіви

**Comment by vtarnay** [comment]
2 іконки відправив на пошту Андрію

**Comment by andy-vin** [comment]
готово - http://prntscr.com/c9dn0l

**Comment by vtarnay** [comment]
Done
