### ISSUE TITLE
Футер вилазить на верх

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#321]
![image](https://cloud.githubusercontent.com/assets/18250100/17804360/fdb56d1a-6603-11e6-8a76-18f7b128db69.png)
![image](https://cloud.githubusercontent.com/assets/18250100/17804367/03b16cbe-6604-11e6-953c-7522821e1ad1.png)

**Comment by Sorey** [comment]
Усе працює нормально!
![2016-08-19 17 50 51](https://cloud.githubusercontent.com/assets/11901700/17814000/6ebe867c-6636-11e6-9e46-4edff34c6048.png)

**Comment by andy-vin** [comment]
почистити кеш, скинути ассети, перевірити - помилка присутня й досі

**Comment by vtarnay** [comment]
done
