### ISSUE TITLE
Модуль порівняння бюджетів (пофіксити логіку довжини гістограми)

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#329]
логіку побудови довжини гістограми взяти за аналогією з логікою гістограми модулю Бюджет (запитати у Валери)
![logic](https://cloud.githubusercontent.com/assets/18190755/17814695/b5ee2cac-6639-11e6-8207-ad688dc8cc7d.png)

**Comment by andy-vin** [comment]
готово - http://prntscr.com/c9bmfo

**Comment by vtarnay** [comment]
done
