### ISSUE TITLE
1) Вигрузка Громадського бюджету в pdf: текстовий блок, модуль показники, модуль бюджет, модуль бюджетний календар, модуль sankey, модуль програми, 

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#33]

**Comment by Quicks** [comment]
Настроил pdf
можно пробовать создавать pdf

**Comment by karelin2005** [comment]
![image 4](https://cloud.githubusercontent.com/assets/18250100/15476397/5c491020-2117-11e6-9868-9376332472ad.jpg)
![image 5](https://cloud.githubusercontent.com/assets/18250100/15476396/5c484622-2117-11e6-848b-3cdfd455e627.jpg)

**Comment by karelin2005** [comment]
При введении данных при создании, изменяются данные на титульном листе

**Comment by karelin2005** [comment]
![image 3](https://cloud.githubusercontent.com/assets/18250100/15819454/eb71b7b4-2beb-11e6-9518-2b4cbc2782a6.jpg)
![image 1](https://cloud.githubusercontent.com/assets/18250100/15819455/eb742652-2beb-11e6-836e-8b33ce44f60a.jpg)
![image 2](https://cloud.githubusercontent.com/assets/18250100/15819456/eba020cc-2beb-11e6-9934-69a765a67eea.jpg)
4. Вставити сторінку, на якій автоматично буде додаватися зміст.
5. Можливість додавати окремі розділи.
6. Якість зберігання PDF та скріншотів 300 dpi
7. Кольористика, щоб зберігалася у CMYK.

**Comment by karelin2005** [comment]
Поле зміст формування автоматично
