### ISSUE TITLE
Прикрутити дизайн Кульчицього по авторизації

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#339]

**Comment by vtarnay** [comment]
![registration](https://cloud.githubusercontent.com/assets/18190755/18213305/3d3a7cb2-7150-11e6-934c-b86599b93114.jpg)
![password](https://cloud.githubusercontent.com/assets/18190755/18213306/3d516706-7150-11e6-841f-86b4d1769237.jpg)
![2](https://cloud.githubusercontent.com/assets/18190755/18213308/3d62363a-7150-11e6-858e-791b4349bfee.jpg)
![1](https://cloud.githubusercontent.com/assets/18190755/18213307/3d5f2fc6-7150-11e6-8ff4-f3fbd930cbf5.jpg)

**Comment by andy-vin** [comment]
готово
![2016-09-27 01-49-20](https://cloud.githubusercontent.com/assets/9365629/18854509/aad269e4-8454-11e6-8127-2b42b57f784a.png)
![2016-09-27 01-49-01](https://cloud.githubusercontent.com/assets/9365629/18854510/aaebe662-8454-11e6-98f7-6cf7e3ad6c32.png)
![2016-09-27 01-48-14](https://cloud.githubusercontent.com/assets/9365629/18854511/aafb839c-8454-11e6-8d15-3d3e3455aeb6.png)

**Comment by vtarnay** [comment]
Done
