### ISSUE TITLE
Модуль бюджетний календарь - виправити легенду

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#342]
![legend](https://cloud.githubusercontent.com/assets/18190755/17889856/00bf1ed6-693b-11e6-9384-edc4e2cc7cda.png)

**Comment by Sorey** [comment]
Ви впевнені що треба видалити "Не вказано"?
Перегляньте полилання: 
- управління календарем - http://prntscr.com/c9c9uq
- створення редагування типової дії - http://prntscr.com/c9caoj

**Comment by vtarnay** [comment]
До речі в модулі зараз трохи порушена логіка.
Правильна логіка:
1) Заносимо дії влади;
2) Дії громадських активістів привязуються до етапів бюджетного процесу.
3) Опишу це окремим issue

**Comment by Sorey** [comment]
Готово - http://prntscr.com/cap2k1

**Comment by vtarnay** [comment]
Done
