### ISSUE TITLE
В профілі міста - посилання (додати поле опису)

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#346]
![links](https://cloud.githubusercontent.com/assets/18190755/17892319/645cca7a-6949-11e6-98a6-32e1eca59b51.png)

**Comment by vtarnay** [comment]
довгі лінки пробивають бочину сайту зправа 
![default](https://cloud.githubusercontent.com/assets/18190755/17961022/04019858-6ab2-11e6-93a6-5c506cbd26ec.png)

**Comment by Sorey** [comment]
Готово
Форма - http://prntscr.com/caozmo
В профілі міста - http://prntscr.com/cap0oj

**Comment by vtarnay** [comment]
Done
