### ISSUE TITLE
Профіль міста - пропала кнопка з профілю міста яка б генерувала ембед-код профілю міста

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#348]
В попередньому дизайні (до того як прикрутили дизайн Кульчицького) була кнопка що робила фрейм з профілю міста, ми її описали в інструкції по користуванню, при переносі дизайна вона загубилася.
![knopka](https://cloud.githubusercontent.com/assets/18190755/17893457/76d8598a-694e-11e6-9aa7-f70826a5931d.png)

**Comment by andy-vin** [comment]
в лінку засунути все, що вкладене в блок "wrapper"

**Comment by andy-vin** [comment]
готово - http://prntscr.com/ckk6gt

**Comment by vtarnay** [comment]
Done
