### ISSUE TITLE
(перший пріоритет) CMS неможливо додати новий розділ - видає помилку

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#349]
Хотів зробити розділ ключові документи і помістити його в громадський контроль. Але при спробі - видає помилку.

![razdel](https://cloud.githubusercontent.com/assets/18190755/17897374/a61a43c6-695c-11e6-9647-cf785e998836.png)

**Comment by vtarnay** [comment]
Потім до цього розділу потрібно буде прикрутити розділ документи, який зараз є але не для пабліка. Опишу цей кейс окремим ішюсом

**Comment by andy-vin** [comment]
готово - http://prntscr.com/ca8wpb

**Comment by vtarnay** [comment]
все -ок
