### ISSUE TITLE
В пошуку не відображаються міста по яким є інфомрація (Чернігів і Житомир)

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#351]
виявлено що не відлбражаються чернігів та житомир
![chernigiv](https://cloud.githubusercontent.com/assets/18190755/17961290/8ae4f86e-6ab3-11e6-8468-7d8ec7f2b05d.png)
![zhut](https://cloud.githubusercontent.com/assets/18190755/17961297/8cc385e2-6ab3-11e6-8f27-86a031f57047.png)

**Comment by andy-vin** [comment]
перевірити ролі у користувачів
