### ISSUE TITLE
Баг з банерами не працює ссилка 

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#365]
![baner](https://cloud.githubusercontent.com/assets/18190755/18004893/7a27ac64-6b9f-11e6-95d3-62904784adab.png)

**Comment by Sorey** [comment]
Готово
![screenshot](https://cloud.githubusercontent.com/assets/11901700/18089022/83e842a2-6ec6-11e6-8b53-99a2c597cb7b.png)

**Comment by vtarnay** [comment]
На тестовому серваку не вдалося загрузити банер! Видає помилку!  ![testovuj servak](https://cloud.githubusercontent.com/assets/18190755/18213793/9df05ab6-7152-11e6-846d-479642444b74.png)

**Comment by andy-vin** [comment]
на тестовому серваку місця як небуло раніше для завантаження малюнків так і зараз немає - повинно працювати завантаження на продакшені. Після перезаливки - перевірити

**Comment by vtarnay** [comment]
готово
