### ISSUE TITLE
(URGENT!) В модулі PDF неможливо додати візуалізацію

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#370]
![bug1](https://cloud.githubusercontent.com/assets/18190755/18058833/ce1767ac-6e1e-11e6-8348-6a4944167bff.png)

**Comment by Quicks** [comment]
готово 
![screenshot](https://cloud.githubusercontent.com/assets/10288310/18239826/89c168aa-7350-11e6-9590-3d759d371d73.png)

**Comment by vtarnay** [comment]
не получається на продашні  :( ![citizens budget](https://cloud.githubusercontent.com/assets/18190755/18643827/744172e4-7eaf-11e6-80d0-a3ee4fe508de.png)

**Comment by Quicks** [comment]
Готово

**Comment by vtarnay** [comment]
Done
