### ISSUE TITLE
Ключовs показники міста Львова

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#372]
Є проблеми із завантаженням ключових показників. 
1. Як створити нову групу показників "Екологія".
2. Чому деякі дані не вносяться, хоча вони є по роках. 
3. Створюється візуалізація але без плавних ліній. 

[key_indicators_2013_2014_Львів.xlsx](https://github.com/kavaleriy/budget/files/444609/key_indicators_2013_2014_.xlsx)

[ключ_Львів.xlsx](https://github.com/kavaleriy/budget/files/444610/_.xlsx)

**Comment by vtarnay** [comment]
Як вияснилося працює також така логіка підгрузки, але в візуалізаціях куча багів, щас опишу їх
[2012_Lviv_1.xlsx](https://github.com/kavaleriy/budget/files/444828/2012_Lviv_1.xlsx)

**Comment by vtarnay** [comment]
https://github.com/kavaleriy/budget/issues/375
https://github.com/kavaleriy/budget/issues/376
