### ISSUE TITLE
Add link to "our partner" item

### ISSUE THREAD

**Issue by andy-vin** [kavaleriy/budget#374]
Add target href to some link in form.
Action: on-click - open new tab, render href value from "Our Partner's" item
Hide pointer on hover, if href doesn't exist into item.
![screenshot](https://cloud.githubusercontent.com/assets/9365629/18089191/66bb7f4a-6ec7-11e6-8053-7fe591e306b0.png)

**Comment by Sorey** [comment]
Готово.
![screenshot 1](https://cloud.githubusercontent.com/assets/11901700/18119260/741c768a-6f62-11e6-9608-ae3b8ad97639.png)

**Comment by vtarnay** [comment]
Done
