### ISSUE TITLE
(Urgent!) Додати можливість редагувати інструкції з користування модулями

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#377]
![instructions](https://cloud.githubusercontent.com/assets/18190755/18091891/fbdf0492-6ed2-11e6-8732-5cee51eeaebe.png)

**Comment by Sorey** [comment]
Готово
http://prntscr.com/crz1k7

Інструкція завантаження файлу: 
http://prntscr.com/crz4td
http://prntscr.com/crz6ja
http://prntscr.com/crz7gy

Посилання на нові інструкцій:
http://openbudget.in.ua/instructions/budget_file_help?locale=uk
http://openbudget.in.ua/instructions/key_indicator_file_help?locale=uk
http://openbudget.in.ua/instructions/repairing_maps_help?locale=uk

Посилання на старі зразки інструкцій:
1)
http://openbudget.in.ua/static/budget_file_help?locale=en
http://openbudget.in.ua/static/budget_file_help?locale=uk
2)
http://openbudget.in.ua/static/key_indicator_file_help?locale=en
http://openbudget.in.ua/static/key_indicator_file_help?locale=uk
3)
http://openbudget.in.ua/repairing/maps/instruction?locale=en
http://openbudget.in.ua/repairing/maps/instruction?locale=uk

**Comment by vtarnay** [comment]
Done
