### ISSUE TITLE
(URGENT!) Модуль типовий профіль міста не працює в Firefox

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#378]
http://openbudget.in.ua/public/towns/55a808b36b61730709485200?locale=uk
![firefox](https://cloud.githubusercontent.com/assets/18190755/18091932/1de8b9f2-6ed3-11e6-8ac7-4f3817fc4c66.png)

**Comment by andy-vin** [comment]
Готово
![screenshot from 2016-09-19 15 52 55](https://cloud.githubusercontent.com/assets/9365629/18632659/37738a6a-7e81-11e6-9168-0d8eec8786ac.png)
![screenshot from 2016-09-19 15 52 08](https://cloud.githubusercontent.com/assets/9365629/18632661/3af7d718-7e81-11e6-8811-e1470ad30e19.png)

**Comment by vtarnay** [comment]
Done
