### ISSUE TITLE
У алгоритмі змін до плану (файли FZ) старий файл видаляти, а новий записувати.

### ISSUE THREAD

**Issue by karelin2005** [kavaleriy/budget#38]
Виявилося, що остаточні файли можуть змінюватися і по часу буває, що пізніше до казначейства відправляються файли, виправлені. Тому для того, щоб математика була правильна, необхідно старі файли видаляти, а нові записувати. Щоб машина, кожного разу перераховувала зміни до плану.

**Comment by kavaleriy** [comment]
готово
