### ISSUE TITLE
Бібліотека відвалилась

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#381]
![biblioteka](https://cloud.githubusercontent.com/assets/18190755/18095955/4f8056d8-6ee1-11e6-8483-2f51ba705d50.png)

**Comment by Sorey** [comment]
Я розумію що книги взагалі забрати здійснювати перехід при кліку на "Бібліотека"
Опишіть бажану поведінку.

**Comment by vtarnay** [comment]
Не зрозумів, щодо бібліотеки.
Питання було в натягуванні дизайну на неї, який зробив Кульчицький.
Зараз при кліку видає помилку.

**Comment by Sorey** [comment]
Готово
Бібліотека відображається.

**Comment by vtarnay** [comment]
Дизайн не підтягується
[Library.pdf](https://github.com/kavaleriy/budget/files/452516/Library.pdf)

**Comment by vtarnay** [comment]
done
