### ISSUE TITLE
Англійська локалізація мапи

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#388]
Замінити скорочення Thous. на К,М,В

![image 7](https://cloud.githubusercontent.com/assets/18250100/18124778/5f3da1a2-6f7c-11e6-9154-31dc81b8297f.jpg)

**Comment by karelin20005** [comment]
Перекласти в редагуванні слоїв "Розрахувати дорогу"
![modul maps pic9](https://cloud.githubusercontent.com/assets/18250100/18126376/836636fa-6f83-11e6-8ae5-7301f4d61ee3.jpg)

**Comment by karelin20005** [comment]
Перекласти в embeded code "Рік" і "Масштаб"
![modul maps pic11](https://cloud.githubusercontent.com/assets/18250100/18128394/2179fb92-6f8e-11e6-876b-2d94a4ce1c53.png)

**Comment by karelin20005** [comment]
На профілі міста перекласти хлібну крихту Візуалізація
![image](https://cloud.githubusercontent.com/assets/18250100/18131548/003e5de8-6f9c-11e6-810b-b2826747212c.png)

**Comment by Sorey** [comment]
Готово
![_016](https://cloud.githubusercontent.com/assets/11901700/18203059/08370810-711d-11e6-8798-9da3cd5d0d19.png)
![_017](https://cloud.githubusercontent.com/assets/11901700/18203062/0b726466-711d-11e6-8757-384c5307558e.png)

**Comment by vtarnay** [comment]
дві мікро правки - в назвах іконок кирилиця висвітлюється
в embed code - кирилиця (виберіть будь ласка 2 символи) 
![pravka1](https://cloud.githubusercontent.com/assets/18190755/18210541/ae9c85bc-7141-11e6-883e-c1e80040d395.png)
![pravka2](https://cloud.githubusercontent.com/assets/18190755/18210542/aeb639d0-7141-11e6-9c36-eca2713f4517.png)

**Comment by vtarnay** [comment]
Змінити в англійській локалізації акронімки дат на латинські ![pravka3](https://cloud.githubusercontent.com/assets/18190755/18210660/4aa03cc4-7142-11e6-8519-80af678ab282.png)

**Comment by Sorey** [comment]
Зроблено:
1)
![fireshot capture 5 - municipal budget](https://cloud.githubusercontent.com/assets/11901700/18276063/201a3974-7452-11e6-86ea-8a7ef1542d8f.png)
2)
![46c8559d1f3f4cf792f8688dfea3ff03](https://cloud.githubusercontent.com/assets/11901700/18276067/254d5eee-7452-11e6-8b5c-007c9492d8aa.png)

Так, іконки не підтягуються тільки на тестовому.
В назвах іконок кирилиця поки що не зроблено.

**Comment by vtarnay** [comment]
Done
