### ISSUE TITLE
Англійська локалізація мапи Перекласти Категорії та "Обрати файл" файл не вибрано

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#389]
![modul maps pic7](https://cloud.githubusercontent.com/assets/18250100/18125966/b53fa0e6-6f81-11e6-85a9-c1cfc8b2f7bc.jpg)

**Comment by Sorey** [comment]
Готово
Дивитись - https://github.com/kavaleriy/budget/issues/503

**Comment by vtarnay** [comment]
Done
