### ISSUE TITLE
Партнери

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#391]
Чи можна прибрати тусклий ефект з логотипів партнерів?
![tysklyj efekt](https://cloud.githubusercontent.com/assets/18190755/18135489/bdfe3f0c-6faa-11e6-928f-08fe89360fa5.png)

**Comment by Sorey** [comment]
Готово
http://prntscr.com/cd7r7m

**Comment by vtarnay** [comment]
done
