### ISSUE TITLE
(нетерміново) Модуль календарь - додати в поле типові дії (можливість вибору часу, поле відповідальний)

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#395]
![calendar6](https://cloud.githubusercontent.com/assets/18190755/18165972/13dfb5da-7051-11e6-9f75-3e6c244ffad1.png)

**Comment by Sorey** [comment]
Зроблено
1) Вдосконалено поле Опису - http://prntscr.com/cfx3sr
2) В цій формі не варто додавати поля из датами, оскільки при створенні події на календарі дата може бути іншого місяця і користувач не помітить як створив подію і де вона зараз.

**Comment by Sorey** [comment]
Готово
http://prntscr.com/ciadni
http://prntscr.com/ciaf28

**Comment by vtarnay** [comment]
done
