### ISSUE TITLE
(нетерміново) В типовому профілі міста при першій загрузці пошук і гедер ведуть себе неправильно

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#396]
![persha](https://cloud.githubusercontent.com/assets/18190755/18167043/26642d02-7057-11e6-9f0f-94a24255145a.png)

**Comment by andy-vin** [comment]
готово
http://prntscr.com/cjsxk5
http://prntscr.com/cjsxqg
http://prntscr.com/cjsxy0
