### ISSUE TITLE
(нетерміново) в Англійській локалізації замінити лого на англійське в футері

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#401]
![horizontal-eng 1](https://cloud.githubusercontent.com/assets/18190755/18197416/b4ea6a02-70ff-11e6-9c98-077d9cf95adb.png)

**Comment by karelin20005** [comment]
У хедері замінити municipal budget на openbudget
![image](https://cloud.githubusercontent.com/assets/18250100/18198076/4497e3fc-7103-11e6-8764-a5df03809930.png)

**Comment by Sorey** [comment]
На темному фоні футера лого Eidos пропадає
Вишліть інше лого подібне до цього (Українська версія):
![eidos-logo](https://cloud.githubusercontent.com/assets/11901700/18204702/c528504c-7126-11e6-8ec5-4e61eb3f2ffe.png)

**Comment by vtarnay** [comment]
сробуйте це
[horizontal-eng-dark-background.zip](https://github.com/kavaleriy/budget/files/452126/horizontal-eng-dark-background.zip)

**Comment by Sorey** [comment]
Ні, там же трикутники не видно.
Відкрийте зразок що я прислав; в ньому видно білу обводку навколо трикутників.

**Comment by vtarnay** [comment]
Переслав Кульчицькому, чекаю відповіді

**Comment by vtarnay** [comment]
Done

**Comment by vtarnay** [comment]
прокосив, не ту таску закрив

**Comment by vtarnay** [comment]
Набери по цьому кейсу, бо вроді всі пишем українською, але ніхрена не зрозуміло, що потрібно. 
098-987-4-987

**Comment by vtarnay** [comment]
![horizontal-eng-dark-backaground](https://cloud.githubusercontent.com/assets/18190755/18242002/df2f2dd4-735c-11e6-8396-16881a2850f0.png)

**Comment by karelin20005** [comment]
У футері замінити Municipal budget на Open Budget
![image](https://cloud.githubusercontent.com/assets/18250100/18244568/6725c156-7369-11e6-99f9-35adcb62a116.png)

**Comment by Sorey** [comment]
Готово
![municipal budget](https://cloud.githubusercontent.com/assets/11901700/18267004/e6d1b952-7425-11e6-9b43-fe7af9c38186.png)

**Comment by vtarnay** [comment]
Done
