### ISSUE TITLE
(Модуль карта) додати леєр Uaroads, дедайлн 16.09.2016

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#411]

**Comment by vtarnay** [comment]
4.09.2016, маю отримати API від Uaroads

**Comment by vtarnay** [comment]
Можливо це також буде корисним (частина маски кілометрових стовпчиків)
http://uaroads.com/repairs-map#
http://uaroads.com/endpoints
оскільки нам потрібно буде заводити дані Мінінфраструктури:
https://docs.google.com/spreadsheets/d/1QMKDdyy5gjZPDYAxJf_O1w1mWOYAId8W5gLvNLDK5kw/htmlview?sle=true#

**Comment by vtarnay** [comment]
API: Інфо, яку Ви просили:
На сторінці http://openbudget.in.ua/repairing/maps/frame/6/55a807aa6b61730709971000/2016

В http://take.ms/YsMKA (58KB)

948 рядку потрібно додати

L.tileLayer('http://map.uaroads.com/pits/1.0.0/{z}/{x}/{y}.png');

**Comment by vtarnay** [comment]
![-](https://cloud.githubusercontent.com/assets/18190755/18668566/dadffffe-7f3e-11e6-9663-f5f1ad96e0b1.jpg)
![uaroads](https://cloud.githubusercontent.com/assets/18190755/18668569/dae2d968-7f3e-11e6-9514-ab963148015e.png)
![-](https://cloud.githubusercontent.com/assets/18190755/18668568/dae2b32a-7f3e-11e6-8111-d3d1d5199c33.jpg)
![navizor_logo](https://cloud.githubusercontent.com/assets/18190755/18668567/dae19350-7f3e-11e6-8523-4b752e8da6e0.png)
![-](https://cloud.githubusercontent.com/assets/18190755/18668570/dae48fd8-7f3e-11e6-9872-7994231efbad.jpg)

[location-on-road.zip](https://github.com/kavaleriy/budget/files/482405/location-on-road.zip)

**Comment by vtarnay** [comment]
[location-on-road-y.zip](https://github.com/kavaleriy/budget/files/482418/location-on-road-y.zip)

**Comment by Quicks** [comment]
готово 
![screenshots](https://cloud.githubusercontent.com/assets/10288310/18741251/be2b3fd0-80b6-11e6-9d27-364b1ee05aa6.png)

**Comment by vtarnay** [comment]
API до Navizora Leaflet navizor.com:8080/osm/{z}/{x}/{y}.png

**Comment by vtarnay** [comment]
Done
