### ISSUE TITLE
Aнглійська локалізація баги.

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#419]
При переході у бібліотеку, з'являється український header&footer.
Також необхідно перекласти хештеги та кнопки 
![image](https://cloud.githubusercontent.com/assets/18250100/18244660/e46927f2-7369-11e6-9aa0-84a46595e08d.png)
У модулі "Бюджет" перекласти кнопку на "Choose file"
![image](https://cloud.githubusercontent.com/assets/18250100/18245521/5a275aa0-736e-11e6-81a5-68fee455bc3e.png)
Те ж саме у модулі програми
![image](https://cloud.githubusercontent.com/assets/18250100/18245977/0b7aa9ea-7371-11e6-8502-549d21ec9cee.png)
Те ж саме у модулі календарі 
![image](https://cloud.githubusercontent.com/assets/18250100/18246025/663f24a0-7371-11e6-8294-50fd746990eb.png)
У модулі "Бюджет"-"Бюджетні файли" при завантажені планових показників і у всіх подібних менюшках замінити на Visualization
![image](https://cloud.githubusercontent.com/assets/18250100/18245574/aa2c2eb8-736e-11e6-8ab0-a97f3637219b.png)
У випадаючому списку замінити Vizuals на Vizualizations
![image](https://cloud.githubusercontent.com/assets/18250100/18245745/a668ce70-736f-11e6-88de-3bfe333dfd22.png)

Повністю не працює модуль у англійській локалізації документи.
![image](https://cloud.githubusercontent.com/assets/18250100/18246110/17b3a170-7372-11e6-8bd4-e85b7a737e3a.png)

**Comment by Sorey** [comment]
Зроблено:
1) Перехід із меню на Бібліотеку з локалізацією
2) http://prntscr.com/ceuejl
3) http://prntscr.com/ceuey0

**Comment by vtarnay** [comment]
"Выбрать файлы" - файл не выбран - залишилися!

**Comment by Sorey** [comment]
Тому я і написав "Зроблено" і перерахував
Коли усе буде зроблено напишу "Готово"

**Comment by vtarnay** [comment]
ok

**Comment by Sorey** [comment]
Зроблено:
4) Список документів відображається

**Comment by Sorey** [comment]
Зроблено:
5) Локаль для форми загрузки файла - http://prntscr.com/cfjcka

**Comment by vtarnay** [comment]
Done
