### ISSUE TITLE
(Баг) Контроль над висотою лого партнерів.

### ISSUE THREAD

**Issue by Sorey** [kavaleriy/budget#423]
(Баг) Висота лого партнера на головній сторінці не контролюється і розтягує блок партнерів.
![municipal budget2](https://cloud.githubusercontent.com/assets/11901700/18269492/ed3a51a4-7430-11e6-9427-b17eabc13522.png)

**Comment by Sorey** [comment]
Готово
![municipal budget](https://cloud.githubusercontent.com/assets/11901700/18269509/03c04870-7431-11e6-9272-70e8314df8c8.png)

**Comment by andy-vin** [comment]
try to use it's logo from scary Internet - http://www.prostir.ua/wp-content/uploads/2016/01/UNDP_logo_UA.png
![undp_logo_ua](https://cloud.githubusercontent.com/assets/9365629/18269624/99181f60-7431-11e6-9079-45bd5d42dde8.png)

**Comment by Sorey** [comment]
Вигляд із більшим лого
![municipal budget3](https://cloud.githubusercontent.com/assets/11901700/18269766/30db45ca-7432-11e6-9175-9bd9e97a1e36.png)

**Comment by vtarnay** [comment]
Done
