### ISSUE TITLE
(Модуль карта) При редагуванні відрізку дороги - пропали картинки

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#424]
![image](https://cloud.githubusercontent.com/assets/18190755/18268090/f37e8c84-742a-11e6-8b27-7ef411e31dad.png)

**Comment by Sorey** [comment]
Готово
![image](https://cloud.githubusercontent.com/assets/11901700/18466603/0c64b758-79a5-11e6-9b4f-a54b72d95497.jpg)

**Comment by vtarnay** [comment]
Іконки всерівно не підтягуються :( 
![icon](https://cloud.githubusercontent.com/assets/18190755/18645121/a5ddc5b4-7eb4-11e6-85de-8b229cc27887.png)
http://openbudget.in.ua/repairing/layers/5766346c67cb7d798c000001?locale=uk

**Comment by vtarnay** [comment]
протестив з новим файлом, іконки не підягуються, лінія між двома точками не промальовується, перестала підтягувати інформація з текстових полів файлу. http://openbudget.in.ua/repairing/layers/57e038e667cb7d0721000001/edit?locale=uk
[Дороги_тест.xlsx](https://github.com/kavaleriy/budget/files/480900/_.xlsx)
![picpic](https://cloud.githubusercontent.com/assets/18190755/18645680/db8ffc70-7eb6-11e6-8536-b6796cb2b9a7.png)

**Comment by Quicks** [comment]
готово. тестуйте
![screenshot 3](https://cloud.githubusercontent.com/assets/10288310/19561517/a9df86a8-96e1-11e6-9315-404fb705aa8d.png)

**Comment by vtarnay** [comment]
done
