### ISSUE TITLE
URGENT! (топовий профіль міста) Поламався модуль документи і потянув за собою карту

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#428]
Було виявлено, що в Дніпропетровській Області - модуль документи відвалився, за словами Андрія це збило всю логіку роботи модулю карти. 

![image](https://cloud.githubusercontent.com/assets/18190755/18273532/5cddaf82-7446-11e6-9cf3-5683f59884a1.png)

**Comment by andy-vin** [comment]
готово, чекає на перезаливку сервера - http://prntscr.com/cesjtr

**Comment by vtarnay** [comment]
Done
