### ISSUE TITLE
URGENT! (фронтпейдж) при заведенні інформації в англійській локалізації відбувається задвоєння розділів для громадян і для чиновників

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#433]
![image](https://cloud.githubusercontent.com/assets/18190755/18280737/d45b3e50-7462-11e6-89f7-c8bbbff42b53.png)

**Comment by vtarnay** [comment]
завів інформацію англійською, спробував видалити розділ для громадян з Розділу ABOUT - видалился і там і на фронтпейджі

**Comment by Sorey** [comment]
Готово
Відновлено info_pages  (Що це дає) в CMS
Управління пунктами головного меню із CMS

**Comment by vtarnay** [comment]
Перевірив. Done
