### ISSUE TITLE
Терміново!!! Повернути на профілі міста вкладинки "Доходи" "Видатки" "Sankey" 

### ISSUE THREAD

**Issue by karelin2005** [kavaleriy/budget#44]
Мені зателефонували вчора з чотирьох міст і сказали, що побилися візуалізації і їм не зрозуміло, як вставляти це на сайт. У двох містах які поставили віджет собі на сторінки, Вони просто не відкриваються видають помилку.

**Comment by Quicks** [comment]
Вернул старый дизайн
