### ISSUE TITLE
(Urgent!) в профілі міста не відображається бюджетний календар!

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#452]
![budget calendar](https://cloud.githubusercontent.com/assets/18190755/18529783/3918a7ae-7ad7-11e6-8712-fbc61dc6a5f0.png)

**Comment by Sorey** [comment]
Готово
http://prntscr.com/cic2wl
http://prntscr.com/cic3w1
Тепер потрібно щоб користувач із містом Маріуполь зайшов на редагування календаря і натиснув Зберегти і цей календар з'явиться у профілі міста Маріуполь. 
*чекбокс "Показати в профілі міста?" повинен бути активований.

**Comment by vtarnay** [comment]
Зайшов пов'язаний бажок - підложка дублюється і іконка неправильна для порівняння міст. Потрібно змінити підложку на цю яка в припріпленому файлі і змінити іконку для порівняння міст (в аттачі)
![calendar](https://cloud.githubusercontent.com/assets/18190755/18579260/3cdd2ad2-7bfd-11e6-8b4f-06af969f850d.jpg)
[bar-chart.zip](https://github.com/kavaleriy/budget/files/476358/bar-chart.zip)

**Comment by andy-vin** [comment]
готово - http://prntscr.com/cio1a5

**Comment by vtarnay** [comment]
картинка календаря не підтягується 
![calendar](https://cloud.githubusercontent.com/assets/18190755/18646143/f5fb3ab4-7eb8-11e6-8ca2-99728719aefe.png)

**Comment by vtarnay** [comment]
Done
