### ISSUE TITLE
нетерміново - в англійській локалізації пофіксити баги з назвами

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#460]
інше - other
Programmatic - Program
![eng](https://cloud.githubusercontent.com/assets/18190755/18595701/8be89e26-7c4e-11e6-9de9-77256351ad87.png)
Who is on duty today? :)

**Comment by vtarnay** [comment]
В модулі Sunkey ще 3 виправлення
![pic 2](https://cloud.githubusercontent.com/assets/18190755/18596014/e8e81ed4-7c4f-11e6-8561-5007f6c5927f.png)

**Comment by vtarnay** [comment]
Замінити в бюджет- бюджетні файли в англійській локалізації Download на Upload
![upload](https://cloud.githubusercontent.com/assets/18190755/18599063/0c000bd4-7c5f-11e6-9077-74528a026f82.png)

**Comment by vtarnay** [comment]
per householding замінити на per household ![houshold](https://cloud.githubusercontent.com/assets/18190755/18604730/c17cbc22-7c88-11e6-8832-71364c66434d.png)

**Comment by vtarnay** [comment]
В модулі карти:
1) як відобразити назви категорій на англійській?
2) змінити "Вибрати файл" "Файл не вибрано"
![mpas](https://cloud.githubusercontent.com/assets/18190755/18703489/baae6152-7fee-11e6-8d23-ac1139f9959c.png)

**Comment by vtarnay** [comment]
![pzdc](https://cloud.githubusercontent.com/assets/18190755/18728378/a6110986-8055-11e6-947a-953af7633fa8.png)

**Comment by vtarnay** [comment]
![fff](https://cloud.githubusercontent.com/assets/18190755/18743850/b0956a32-80c3-11e6-94e4-d34125066614.png)

**Comment by vtarnay** [comment]
модуль календарь, в типових діях додати нову дію
![brr](https://cloud.githubusercontent.com/assets/18190755/18810150/59885ce2-8297-11e6-8e76-0f762a2b05e8.png)

**Comment by vtarnay** [comment]
![citizens](https://cloud.githubusercontent.com/assets/18190755/18810721/ffcbbce4-82a5-11e6-9c3b-4b7fe815c4a3.png)

**Comment by Sorey** [comment]
Все готово крім:
В модулі карти:
1) як відобразити назви категорій на англійській?
2) змінити "Вибрати файл" "Файл не вибрано"

Виніс це на окрему таску - https://github.com/kavaleriy/budget/issues/503

**Comment by vtarnay** [comment]
done
