### ISSUE TITLE
Новий дизайн для Бібліотеки

### ISSUE THREAD

**Issue by Sorey** [kavaleriy/budget#462]
https://github.com/kavaleriy/budget/files/452516/Library.pdf

**Comment by Sorey** [comment]
Готово
1) Вигляд для зареєстрованого користувача або адміна
http://prntscr.com/cl4z2u
http://prntscr.com/cl4zma
http://prntscr.com/cl52an
2) Вигляд для не зареєстрованого користувача
http://prntscr.com/cl5196

**Comment by vtarnay** [comment]
не працює на продашні

**Comment by vtarnay** [comment]
![library](https://cloud.githubusercontent.com/assets/18190755/19031333/40aa7b6c-895c-11e6-865d-f45289609c93.png)

**Comment by vtarnay** [comment]
1) додати перманенту підсвітку кнопки скачати. 
![bilblioteka](https://cloud.githubusercontent.com/assets/18190755/19069086/0833f3bc-8a2e-11e6-9f2e-faa260723938.png)

**Comment by Sorey** [comment]
Тобто подібним кольором зробити фон і при наведенні він змінює відтінок?

**Comment by vtarnay** [comment]
хай буде перманенто жовтий без зміни кольору

**Comment by Sorey** [comment]
Зрозумів.

**Comment by Sorey** [comment]
Готово
http://prntscr.com/cpo7zl

**Comment by vtarnay** [comment]
Done
