### ISSUE TITLE
(модуль карта) в профілі міста на модулі карта замість леєрів конкретного міста відображаються всі обєкти

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#466]
всі обєкти повинні відображатися тільки в профілі "Демонстрація типового профілю міста
![dnipro](https://cloud.githubusercontent.com/assets/18190755/18669303/f5d66466-7f42-11e6-8aa1-e6ac2208f6e2.png)
"

**Comment by Sorey** [comment]
Готово

**Comment by vtarnay** [comment]
не працює
![bug](https://cloud.githubusercontent.com/assets/18190755/19031276/e956e274-895b-11e6-953c-67ebbd5664f3.png)

**Comment by vtarnay** [comment]
Done
