### ISSUE TITLE
Urgent! Не видає мапу на віджетах, блокується сценарій.

### ISSUE THREAD

**Issue by karelin20005** [kavaleriy/budget#487]
![image](https://cloud.githubusercontent.com/assets/18250100/18904934/4ce8f328-8569-11e6-80eb-56f785429d94.png)

**Comment by karelin20005** [comment]
https://city-adm.lviv.ua/public-information/budget/2016/1018?fullpage=1

**Comment by djadjaGrisha** [comment]
Зроблено.
Після оновлення продакшину потрібно буде ще раз скопіювати код для вставки з нашого ресурсу

**Comment by vtarnay** [comment]
Done
