### ISSUE TITLE
Локалізація для Категорій ремонтів

### ISSUE THREAD

**Issue by Sorey** [kavaleriy/budget#503]
Англійська локалізація для Категорій ремонтів - https://cloud.githubusercontent.com/assets/18190755/18703489/baae6152-7fee-11e6-8d23-ac1139f9959c.png
Настройка вибору категорій у селектах по проекту - https://github.com/kavaleriy/budget/issues/389

**Comment by Sorey** [comment]
Готово
Категорії ремонтів:
http://prntscr.com/cq1v22
http://prntscr.com/cq1vcz

http://prntscr.com/cq1rz7
http://prntscr.com/cq1rsk

Селект категорій:
http://prntscr.com/cq1vzs
http://prntscr.com/cq1ssw

**Comment by Sorey** [comment]
Слої:
http://prntscr.com/cq1x11
http://prntscr.com/cq1x6k

**Comment by vtarnay** [comment]
Done
