### ISSUE TITLE
Юзери з одного міста бачать файли один одного

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#51]
юзери можуть правити і видаляти файли один одного в межах одного міста.
я створив тестовий акаунт і присвоїв йому місто Київ - заапрувив через адмінку. Коли логінюся під тестовим містом - бачу файли які завантажені під м. Київ та можу їх правити\видаляти - це потрібно пофіксити.
![bug1](https://cloud.githubusercontent.com/assets/18190755/14577672/7e55148a-037f-11e6-9996-2d7bc6cf565b.png)

**Comment by Quicks** [comment]
Fix
77be26f9ef6faea7383ae73304afd3bcfce98c25
