### ISSUE TITLE
Run tasks after merge branch dev_week_40

### ISSUE THREAD

**Issue by andy-vin** [kavaleriy/budget#523]
1) bundle install
2) rake content_page:create_instructions_page RAILS_ENV=production
3) rake content_page:create_instruction_pages RAILS_ENV=production

**Comment by Sorey** [comment]
rake repairing_categories:add_locale_field RAILS_ENV=production
rake repairing_layers:add_locale_field RAILS_ENV=production

**Comment by andy-vin** [comment]
Done
