### ISSUE TITLE
Urgent!  ембед групи візуалізацій задвоює www.openbudget

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#533]
на прикладі міста Суми
![embed](https://cloud.githubusercontent.com/assets/18190755/19484846/b326379c-9561-11e6-94d9-f377d6961c7c.png)

замість <iframe class="embed-responsive-item" frameborder="0" height="611px" src="**http://openbudget.in.ua**/widgets/town/profile/573c249f67cb7d072000006a?locale=uk" width="100%"></iframe>

вставляє <iframe class="embed-responsive-item" frameborder="0" height="611px" src="**http://openbudget.in.uahttp://openbudget.in.ua**/widgets/town/profile/573c249f67cb7d072000006a?locale=uk" width="100%"></iframe>

Код чомусь не показується, але нас цим не злякаєш
![vrjow-nevozjmew](https://cloud.githubusercontent.com/assets/18190755/19485082/9cb2d8d4-9562-11e6-930f-c3faa6f21a14.png)

**Comment by Sorey** [comment]
Готово.
