### ISSUE TITLE
Urgent! (Модуль Карта) в кнопці код для вбудови зламався вибір міста

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#534]
Всі коди для вбудови центрують на центрі України замість обраного міста, также при виборі міста в меню вибору і переходу на карту в кнопку код для вбудови не підтягується обране місто. 
![karta](https://cloud.githubusercontent.com/assets/18190755/19485173/ec829cc8-9562-11e6-9d67-b26382eb5832.png)

**Comment by Sorey** [comment]
Готово.
