### ISSUE TITLE
В англійській локалізації є такі розділи до яких нема доступу з меню для редагування

### ISSUE THREAD

**Issue by vtarnay** [kavaleriy/budget#58]
Видалити їх я теж не можу
![eng](https://cloud.githubusercontent.com/assets/18190755/14587208/ced00cc4-04b7-11e6-97f2-48ff1e8b87aa.png)

**Comment by Quicks** [comment]
Зробив можливість видаляти сторінки без заголовку( вони помічені як 'empty').
![Uploading Selection_002.png…]()

Також виключив можливість створення сторінки без заголовку і контенту

**Comment by vtarnay** [comment]
Всерівно немає доступу до цих сторіночок, в меню контент їх нема.
вони перемістилися в українську локалізацію
![default](https://cloud.githubusercontent.com/assets/18190755/14605378/f643225e-0580-11e6-9f89-5558d99eca16.png)
