### ISSUE TITLE
Локализация модулей на en

### ISSUE THREAD

**Issue by kavaleriy** [kavaleriy/budget#81]

**Comment by karelin2005** [comment]
![image 3](https://cloud.githubusercontent.com/assets/18250100/15476163/48da720a-2116-11e6-80d9-50b2842eee14.jpg)
![image 1](https://cloud.githubusercontent.com/assets/18250100/15476162/48d3d0b2-2116-11e6-9956-08f951af273a.jpg)
![image 2](https://cloud.githubusercontent.com/assets/18250100/15476164/48e0f6e8-2116-11e6-9ed8-da20a0019784.jpg)

**Comment by karelin2005** [comment]
Поправить аглийскую локализацию

**Comment by Sorey** [comment]
Я перевел инструкцию Справочника работ. http://openbudget.in.ua/repairing/maps/instruction?locale=en
Так же я перевел содержание футера. Его тоже посмотрите.
