### ISSUE TITLE
Карта ремонтів баги та фікси

### ISSUE THREAD

**Issue by karelin2005** [kavaleriy/budget#88]
![image 3](https://cloud.githubusercontent.com/assets/18250100/15535985/4442cbc6-2278-11e6-9ce1-d1c0bced5763.jpg)
![image 1](https://cloud.githubusercontent.com/assets/18250100/15535987/446b0fe6-2278-11e6-99fe-709dca388675.jpg)
![image 2](https://cloud.githubusercontent.com/assets/18250100/15535988/446c6f8a-2278-11e6-965b-4b2a213a7875.jpg)

**Comment by kavaleriy** [comment]
Готово
