### ISSUE TITLE
Карта ремонтів баги та фікси

### ISSUE THREAD

**Issue by karelin2005** [kavaleriy/budget#92]
1. Не можу додати об'єкт дороги на мапі у редакторі. Не працює кнопка зберегти.
2. Якщо, є спроба додати дорогу, то зникає повністю об'єкти на мапі після цього
![image 1](https://cloud.githubusercontent.com/assets/18250100/16005471/2662c168-3170-11e6-8b12-0ef6fed49e5f.jpg)

**Comment by karelin2005** [comment]
Не пише Збережено.

**Comment by Quicks** [comment]
Додав повідомлення
